import ctypes, sys, os, urllib.request, time, zipfile
os.system("taskkill /f /im SCNAV.exe")
userpf = os.environ['USERPROFILE']

def is_admin():
    try:
        return ctypes.windll.shell32.IsUserAnAdmin()
    except:
        print("error on figuring out if the installer is admin!")
        return False

if is_admin():
    print("Checking if SCNAV is running to install...")
    os.system("taskkill /f /im SCNAV.exe")
    print("Super Cool Nice Anti-Virus 2025 Edition installer")
    print("""
     DVD Installer version 3.0                                                                                                                                                                                                                               
""")
    print("Copyright (C) Backdoor Interactive 2025")
    print("This software is entirely Free. including no annoyances what so ever! (except for silly intentional ones xdd)")
    print("Scan your PC for viruses and malware by checking over 32 million hashes. SCNAV currently has tons malware hashes in the bases!")
    print("")
    print("Will install to C:\Program Files\SCNAV2025")
    print("Checking if already installed please wait...")
    # Delay seems nice here. Makes it seem more real
    time.sleep(5)
    maindir = 'C:\\Program Files\\SCNAV2025'
    maindirqu = '"C:\\Program Files\\SCNAV2025"' # kinda pointless to have this in a var. but here if needed for future features
    osk = '"C:\\Program Files\\SCNAV2025\\osk"' # kinda pointless to have this in a var. but here if needed for future features
    os.system(f'mkdir {maindirqu}') 
    print("Now installing SCNAV 2025")
    print("Copying SCNAV.exe")
    os.system(f'copy SCNAV.exe {maindirqu}')
    print("Copying update.exe")
    os.system(f'copy update.exe {maindirqu}')
    print("Copying ver.txt")
    os.system(f'copy ver.txt {maindirqu}')
    print("Copying scan.exe")
    os.system(f'copy scan.exe {maindirqu}')
    print("Copying remove.exe")
    os.system(f'copy remove.exe {maindirqu}')
    print("Copying settings.exe")
    os.system(f'copy settings.exe {maindirqu}')
    print("Copying scansettings.txt")
    os.system(f'copy scansettings.txt {maindirqu}')
    print("Copying scnavrealtime.exe")
    os.system(f'copy scnavrealtime.exe {maindirqu}')
    print("Copying param.vbs")
    os.system(f'copy param.vbs {maindirqu}')
    print("Copying internet.vbs")
    os.system(f'copy internet.vbs {maindirqu}')
    print("Copying vt.vbs")
    os.system(f'copy vt.vbs {maindirqu}')
    print("Copying scnfinish.wav")
    os.system(f'copy scnfinish.wav {maindirqu}')
    print("Copying scanneddirs.txt")
    os.system(f'copy scanneddirs.txt {maindirqu}')
    print("Copying threats.txt") 
    os.system(f'copy threats.txt {maindirqu}')
    print("Copying threatsexe.txt") 
    os.system(f'copy threatsexe.txt {maindirqu}')
    print("Copying scanhistory.txt")
    os.system(f'copy scanhistory.txt {maindirqu}')
    print("Copying sand.exe")
    os.system(f"copy sand.exe {maindirqu}")
    print("Copying sscan.exe")
    os.system(f'copy sscan.exe {maindirqu}')
    print("Copying sremove.exe")
    os.system(f'copy sremove.exe {maindirqu}')
    time.sleep(1)
    print("Copying server.exe")
    os.system(f'copy server.exe {maindirqu}')
    print("Copying client.exe")
    os.system(f'copy client.exe {maindirqu}')
    print("Copying netconf.txt")
    os.system(f'copy netconf.txt {maindirqu}')
    print("Copying threat.mp3")
    os.system(f'copy threat.mp3 {maindirqu}')
    os.system(f'mkdir {osk}') 
    print(f"Installing SCNAV Virtual Keyboard into {maindir}\\osk")
    os.system(f'xcopy osk {osk} /s /e /h')
    print("Copying Super Cool Nice Antivirus 2025.lnk (Shortcut file)")
    os.system(f'copy shortcut.lnk {maindirqu}')
    print("Checking Malware bases status! (is it already installed? Is this a newer version?)")
    print("Good to go!")
    print("Preparing to copy the Malware MD5 Hash Database... (1.1gb)")
    time.sleep(3)
    print("Copying Malware database This will take a while! Do not close this window!")
    os.system(f'copy bases.txt {maindirqu}')
    print("Copy complete! Verifying database integrity (This wont take long!)")
    time.sleep(5)
    os.system(f'copy basever.txt {maindirqu}')

    with open(os.path.join(maindir, 'basever.txt'), 'r') as file:
        line = file.readline()
        print(line)
    time.sleep(2)
    print("")
    print("SCNAV Malware Database installed / updated sucessfully")
    os.system("reg import rc.reg")
    time.sleep(3)
    os.chdir(maindir) 
    print("Copying SCNAV shortcut to desktop")
    os.system(f'copy "shortcut.lnk" "{userpf}\\Desktop\\Super Cool Nice Antivirus 2025.lnk"')
    print("")
    print("Installation Complete!")
    print("Thank you for installing Super Cool Nice Antivirus 2025")
    print("We hope that you enjoy using this silly ( But professional~~ ) antivirus! Ha ha ha!")
    print("Tip! SCNAV May think the system is at risk! This is due that you have no scans completed! (yet)\n Scan the system once to calm everything down")
    print("Press ENTER to Exit")
    a = input("")
    sys.exit()

else:
    # Didnt run as admin, Ask for admin and rerun
    print("SCNAV Installer needs administrator previlages to run!")
    time.sleep(3)
    ctypes.windll.shell32.ShellExecuteW(None, "runas", sys.executable, " ".join(sys.argv), None, 1)
