import ctypes, sys, os, urllib.request, time, zipfile
os.system("taskkill /f /im SCNAV.exe")
userpf = os.environ['USERPROFILE']

def is_admin():
    try:
	    return 1
        # ctypes.windll.shell32.IsUserAnAdmin()
    except:
        print("error on figuring out if the installer is admin!")
        return False

if is_admin():
    print("Super Cool Nice AntiVirus 2025 Edition installer")
    print("""
     DVD Installer version 4.0                                                                                                                                                                                                                               
""")
    print("Copyright (C) Backdoor Interactive! 2026")
    print("This software is entirely Free.")
    print("Scan your PC for viruses and malware by checking over 32 million hashes. SCNAV currently has tons malware hashes in the bases!")
    print("")
    print("Installation Directory: C:\Program Files\SCNAV2025")
    print("Checking system requirements please wait...")
    # Delay seems nice here. Makes it seem more realistic
    time.sleep(5)
    maindir = 'C:\\Program Files\\SCNAV2025'
    maindirqu = '"C:\\Program Files\\SCNAV2025"' # Install directory with quotes (because of the space)
    maindirpy = '"C:\\Program Files\\SCNAV2025\\py32"' # Install directory with quotes (because of the space)
    osk = '"C:\\Program Files\\SCNAV2025\\osk"' # kinda pointless to have this in a var. but here if needed for future features
    os.system('mkdir ' + maindirqu) 
    os.system('mkdir ' + maindirpy)
    print("Now installing SCNAV 2025")
    print("Copying SCNAV.exe")
    os.system('copy SCNAV.exe ' + maindirqu)
    print("Copying update.bat")
    os.system('copy update.bat ' +maindirqu)
    print("Copying scan.bat")
    os.system('copy scan.bat ' +maindirqu)
    print("Copying sscan.bat")
    os.system('copy sscan.bat ' +maindirqu)	
    print("Copying remove.bat")
    os.system('copy remove.bat ' +maindirqu)
    print("Copying settings.bat")
    os.system('copy settings.bat ' +maindirqu)
    print("Copying shredfile.bat")
    os.system('copy shredfile.bat ' +maindirqu)
    print("Copying scnavrealtime.bat")
    os.system('copy scnavrealtime.bat ' +maindirqu)
    print("Copying shredfold.bat")
    os.system('copy shredfold.bat ' +maindirqu)

    print("Copying ver.txt")

    print("Copying scnav.bat")
    os.system('copy scnav.bat ' + maindirqu)
    print("Copying elevate.exe")
    os.system('copy elevate.exe ' + maindirqu)
    print("Copying scan.pyc")
    os.system('copy scan.pyc ' + maindirqu)
    print("Copying remove.pyc")
    os.system('copy remove.pyc ' + maindirqu)
    print("Copying settings.pyc")
    os.system('copy settings.pyc ' + maindirqu)
    print("Copying shred.pyc")
    os.system('copy shred.pyc ' +maindirqu)
    print("Copying update.pyc")
    os.system('copy update.pyc ' +maindirqu)
    print("Copying scnavrealtime.pyc")
    os.system('copy scnavrealtime.pyc ' +maindirqu)
	
    print("Copying scansettings.txt")
    os.system('copy scansettings.txt ' + maindirqu)
    print("Copying ver.txt")
    os.system('copy ver.txt ' + maindirqu)
    print("Copying internet.vbs")
    os.system('copy internet.vbs ' + maindirqu)
    print("Copying scnfinish.wav")
    os.system('copy scnfinish.wav '+maindirqu)
    #print("Copying scanneddirs.txt")
    #os.system('copy scanneddirs.txt '+maindirqu)
    #print("Copying threats.txt") 
    #os.system('copy threats.txt '+ maindirqu)
    #print("Copying threatsexe.txt") 
    #os.system('copy threatsexe.txt '+maindirqu)
    #print("Copying scanhistory.txt")
    #os.system('copy scanhistory.txt '+maindirqu)
    
    #print("Copying sand.exe")
    #os.system('copy sand.exe '+maindirqu)
	
    #print("Copying sscan.exe")
    #os.system('copy sscan.exe {maindirqu}')
    #print("Copying sremove.exe")
    #os.system(f'copy sremove.exe {maindirqu}')
    time.sleep(1)
    #print("Copying server.exe")
    #os.system(f'copy server.exe {maindirqu}')
    #print("Copying client.exe")
    #os.system(f'copy client.exe {maindirqu}')
    #print("Copying netconf.txt")
    #os.system(f'copy netconf.txt {maindirqu}')
    print("Copying threat.wav")
    os.system('copy threat.wav '+maindirqu)
    #os.system('mkdir ' + osk) 
    #print(f"Installing SCNAV Virtual Keyboard into {maindir}\\osk")
    #os.system(f'xcopy osk {osk} /s /e /h')
    print("Creating shortcut...")
    os.system('copy shortcut.lnk '+maindirqu)
    time.sleep(3)
    print("Copying Python 3.2 Portable...")
	
    os.system('xcopy py32 ' + maindirpy + ' /s /e /h')
    print("Python 3.2 portable installed into SCNAV2025\py32")
	
    print("Checking Malware database status! (is it already installed? Is this a newer version?)")
    print("Good to go!")
    print("Preparing to copy the Malware MD5 Hash Database... (1.1gb)")
    time.sleep(3)
    print("Copying Malware database This will take a while! Do not close this window!")
    os.system('copy bases.txt '+maindirqu)
    print("Copy complete! Verifying database integrity (This wont take long!)")
    time.sleep(5)
    os.system('copy basever.txt '+ maindirqu)

    with open(os.path.join(maindir, 'basever.txt'), 'r') as file:
        line = file.readline()
        print(line)
    time.sleep(2)
    print("")
    print("SCNAV Malware Database installed / updated sucessfully")
    message = input("Would you like to add SCNAV shortcuts in your Rightclick Context menu?\n(scan this file, scan this directory, etc)\nNote: This feature is only compatible with Windows XP and up.\n [y\n] (n) ")
    if message == "y":
        os.system("reg import rc.reg")
        print("Context menu shortcuts added to registry")
    time.sleep(3)
    os.chdir(maindir) 
    print("Copying SCNAV shortcut to desktop")
    os.system('copy "shortcut.lnk" "'+userpf+'\\Desktop\\Super Cool Nice Antivirus 2025.lnk"')
    print("")
    print("Installation Complete!")
    print("Thank you for installing Super Cool Nice Antivirus 2025")
    print("We hope that you enjoy using your new antivirus!")
    print("Press ENTER to Exit :)")
    a = input("")
    sys.exit()

else:
    # Didnt run as admin, Ask for admin and rerun
    print("SCNAV Installer needs administrator previlages to run!")
    time.sleep(3)
    ctypes.windll.shell32.ShellExecuteW(None, "runas", sys.executable, " ".join(sys.argv), None, 1)
